version: 2
models:
  - name: bridge_track_composer
    description: >
      Bridge model for track and composer,
      M:N relationship with both track_key and composer_key having multiple of each other so bridge_track_composer.track_key
      (FK) -> dim_track.track_key (PK) and bridge_track_composer.composer_key (FK) -> dim_composer.composer_key (PK),
      Grain: 1 row represents 1 unique identifier track_key of track x 1 unique identifier composer_key of composer
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - track_key
              - composer_key 
    columns:
      - name: track_key
        description: >
          Unique identifier for a track
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_track')
                field: track_key

      - name: composer_key
        description: >
          Unique identifier for a composer
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_composer')
                field: composer_key